package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AlbumInfo generated by hbm2java
 */
public class AlbumInfo implements java.io.Serializable {

	private Integer AId;
	private UserInfo userInfo;
	private TagInfo tagInfo;
	private String ADes;
	private Date ACreatetime;
	private String AName;
	private Boolean albumIfsee;
	private Integer ANumber;
	private Set photoInfos = new HashSet(0);
	private Set userHasAlbumInfos = new HashSet(0);

	public AlbumInfo() {
	}

	public AlbumInfo(UserInfo userInfo, TagInfo tagInfo, String ADes,
			Date ACreatetime, String AName, Boolean albumIfsee,
			Integer ANumber, Set photoInfos, Set userHasAlbumInfos) {
		this.userInfo = userInfo;
		this.tagInfo = tagInfo;
		this.ADes = ADes;
		this.ACreatetime = ACreatetime;
		this.AName = AName;
		this.albumIfsee = albumIfsee;
		this.ANumber = ANumber;
		this.photoInfos = photoInfos;
		this.userHasAlbumInfos = userHasAlbumInfos;
	}

	public Integer getAId() {
		return this.AId;
	}

	public void setAId(Integer AId) {
		this.AId = AId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public TagInfo getTagInfo() {
		return this.tagInfo;
	}

	public void setTagInfo(TagInfo tagInfo) {
		this.tagInfo = tagInfo;
	}

	public String getADes() {
		return this.ADes;
	}

	public void setADes(String ADes) {
		this.ADes = ADes;
	}

	public Date getACreatetime() {
		return this.ACreatetime;
	}

	public void setACreatetime(Date ACreatetime) {
		this.ACreatetime = ACreatetime;
	}

	public String getAName() {
		return this.AName;
	}

	public void setAName(String AName) {
		this.AName = AName;
	}

	public Boolean getAlbumIfsee() {
		return this.albumIfsee;
	}

	public void setAlbumIfsee(Boolean albumIfsee) {
		this.albumIfsee = albumIfsee;
	}

	public Integer getANumber() {
		return this.ANumber;
	}

	public void setANumber(Integer ANumber) {
		this.ANumber = ANumber;
	}

	public Set getPhotoInfos() {
		return this.photoInfos;
	}

	public void setPhotoInfos(Set photoInfos) {
		this.photoInfos = photoInfos;
	}

	public Set getUserHasAlbumInfos() {
		return this.userHasAlbumInfos;
	}

	public void setUserHasAlbumInfos(Set userHasAlbumInfos) {
		this.userHasAlbumInfos = userHasAlbumInfos;
	}

}
