package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * FgroupInfo generated by hbm2java
 */
public class FgroupInfo implements java.io.Serializable {

	private Integer fgId;
	private UserInfo userInfo;
	private String fgName;
	private Integer fgNumber;
	private Set friendInfos = new HashSet(0);

	public FgroupInfo() {
	}

	public FgroupInfo(UserInfo userInfo, String fgName, Integer fgNumber,
			Set friendInfos) {
		this.userInfo = userInfo;
		this.fgName = fgName;
		this.fgNumber = fgNumber;
		this.friendInfos = friendInfos;
	}

	public Integer getFgId() {
		return this.fgId;
	}

	public void setFgId(Integer fgId) {
		this.fgId = fgId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public String getFgName() {
		return this.fgName;
	}

	public void setFgName(String fgName) {
		this.fgName = fgName;
	}

	public Integer getFgNumber() {
		return this.fgNumber;
	}

	public void setFgNumber(Integer fgNumber) {
		this.fgNumber = fgNumber;
	}

	public Set getFriendInfos() {
		return this.friendInfos;
	}

	public void setFriendInfos(Set friendInfos) {
		this.friendInfos = friendInfos;
	}

}
