package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * MsgInfo generated by hbm2java
 */
public class MsgInfo implements java.io.Serializable {

	private Integer msgId;
	private UserInfo userInfoByMsgToUserId;
	private UserInfo userInfoByMsgFromUserId;
	private String msgVerify;
	private Date msgCreatetime;
	private Boolean msgFlag;

	public MsgInfo() {
	}

	public MsgInfo(UserInfo userInfoByMsgToUserId,
			UserInfo userInfoByMsgFromUserId, String msgVerify,
			Date msgCreatetime, Boolean msgFlag) {
		this.userInfoByMsgToUserId = userInfoByMsgToUserId;
		this.userInfoByMsgFromUserId = userInfoByMsgFromUserId;
		this.msgVerify = msgVerify;
		this.msgCreatetime = msgCreatetime;
		this.msgFlag = msgFlag;
	}

	public Integer getMsgId() {
		return this.msgId;
	}

	public void setMsgId(Integer msgId) {
		this.msgId = msgId;
	}

	public UserInfo getUserInfoByMsgToUserId() {
		return this.userInfoByMsgToUserId;
	}

	public void setUserInfoByMsgToUserId(UserInfo userInfoByMsgToUserId) {
		this.userInfoByMsgToUserId = userInfoByMsgToUserId;
	}

	public UserInfo getUserInfoByMsgFromUserId() {
		return this.userInfoByMsgFromUserId;
	}

	public void setUserInfoByMsgFromUserId(UserInfo userInfoByMsgFromUserId) {
		this.userInfoByMsgFromUserId = userInfoByMsgFromUserId;
	}

	public String getMsgVerify() {
		return this.msgVerify;
	}

	public void setMsgVerify(String msgVerify) {
		this.msgVerify = msgVerify;
	}

	public Date getMsgCreatetime() {
		return this.msgCreatetime;
	}

	public void setMsgCreatetime(Date msgCreatetime) {
		this.msgCreatetime = msgCreatetime;
	}

	public Boolean getMsgFlag() {
		return this.msgFlag;
	}

	public void setMsgFlag(Boolean msgFlag) {
		this.msgFlag = msgFlag;
	}

}
