package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NoticeInfo generated by hbm2java
 */
public class NoticeInfo implements java.io.Serializable {

	private Integer noticeId;
	private PhotoInfo photoInfo;
	private UserInfo userInfoByUserToUserId;
	private UserInfo userInfoByUserFromUserId;
	private String noticeContent;
	private Boolean flag;
	private Date noticeCreatetime;

	public NoticeInfo() {
	}

	public NoticeInfo(PhotoInfo photoInfo, UserInfo userInfoByUserToUserId,
			UserInfo userInfoByUserFromUserId, String noticeContent,
			Boolean flag, Date noticeCreatetime) {
		this.photoInfo = photoInfo;
		this.userInfoByUserToUserId = userInfoByUserToUserId;
		this.userInfoByUserFromUserId = userInfoByUserFromUserId;
		this.noticeContent = noticeContent;
		this.flag = flag;
		this.noticeCreatetime = noticeCreatetime;
	}

	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	public PhotoInfo getPhotoInfo() {
		return this.photoInfo;
	}

	public void setPhotoInfo(PhotoInfo photoInfo) {
		this.photoInfo = photoInfo;
	}

	public UserInfo getUserInfoByUserToUserId() {
		return this.userInfoByUserToUserId;
	}

	public void setUserInfoByUserToUserId(UserInfo userInfoByUserToUserId) {
		this.userInfoByUserToUserId = userInfoByUserToUserId;
	}

	public UserInfo getUserInfoByUserFromUserId() {
		return this.userInfoByUserFromUserId;
	}

	public void setUserInfoByUserFromUserId(UserInfo userInfoByUserFromUserId) {
		this.userInfoByUserFromUserId = userInfoByUserFromUserId;
	}

	public String getNoticeContent() {
		return this.noticeContent;
	}

	public void setNoticeContent(String noticeContent) {
		this.noticeContent = noticeContent;
	}

	public Boolean getFlag() {
		return this.flag;
	}

	public void setFlag(Boolean flag) {
		this.flag = flag;
	}

	public Date getNoticeCreatetime() {
		return this.noticeCreatetime;
	}

	public void setNoticeCreatetime(Date noticeCreatetime) {
		this.noticeCreatetime = noticeCreatetime;
	}

}
