package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TagInfo generated by hbm2java
 */
public class TagInfo implements java.io.Serializable {

	private Integer tagId;
	private UserInfo userInfo;
	private String tagName;
	private Set albumInfos = new HashSet(0);
	private Set photoInfos = new HashSet(0);

	public TagInfo() {
	}

	public TagInfo(UserInfo userInfo, String tagName, Set albumInfos,
			Set photoInfos) {
		this.userInfo = userInfo;
		this.tagName = tagName;
		this.albumInfos = albumInfos;
		this.photoInfos = photoInfos;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public Set getAlbumInfos() {
		return this.albumInfos;
	}

	public void setAlbumInfos(Set albumInfos) {
		this.albumInfos = albumInfos;
	}

	public Set getPhotoInfos() {
		return this.photoInfos;
	}

	public void setPhotoInfos(Set photoInfos) {
		this.photoInfos = photoInfos;
	}

}
