package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

/**
 * UserHasAlbumInfo generated by hbm2java
 */
public class UserHasAlbumInfo implements java.io.Serializable {

	private Integer uhasaId;
	private UserInfo userInfo;
	private AlbumInfo albumInfo;

	public UserHasAlbumInfo() {
	}

	public UserHasAlbumInfo(UserInfo userInfo, AlbumInfo albumInfo) {
		this.userInfo = userInfo;
		this.albumInfo = albumInfo;
	}

	public Integer getUhasaId() {
		return this.uhasaId;
	}

	public void setUhasaId(Integer uhasaId) {
		this.uhasaId = uhasaId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public AlbumInfo getAlbumInfo() {
		return this.albumInfo;
	}

	public void setAlbumInfo(AlbumInfo albumInfo) {
		this.albumInfo = albumInfo;
	}

}
