package bs.photoAdmin.model;

// Generated 2015-3-18 15:24:14 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UsericonInfo generated by hbm2java
 */
public class UsericonInfo implements java.io.Serializable {

	private Integer iconId;
	private UserInfo userInfo;
	private Date iconCreatetime;
	private String iconImage;

	public UsericonInfo() {
	}

	public UsericonInfo(UserInfo userInfo, Date iconCreatetime, String iconImage) {
		this.userInfo = userInfo;
		this.iconCreatetime = iconCreatetime;
		this.iconImage = iconImage;
	}

	public Integer getIconId() {
		return this.iconId;
	}

	public void setIconId(Integer iconId) {
		this.iconId = iconId;
	}

	public UserInfo getUserInfo() {
		return this.userInfo;
	}

	public void setUserInfo(UserInfo userInfo) {
		this.userInfo = userInfo;
	}

	public Date getIconCreatetime() {
		return this.iconCreatetime;
	}

	public void setIconCreatetime(Date iconCreatetime) {
		this.iconCreatetime = iconCreatetime;
	}

	public String getIconImage() {
		return this.iconImage;
	}

	public void setIconImage(String iconImage) {
		this.iconImage = iconImage;
	}

}
